### ISSUE TITLE
Jedi Knight Outcast VDXR not working, SteamVR very jittery and crashes.

### ISSUE THREAD

**Issue by Zerthick** [DrBeef/JKXR#10]
Hello!

I'm trying to play Jedi Knight Outcast on PCVR with a Meta Quest 3 but running into several issues. VDXR is able to render the game's opening cut scene, however is not able to render the visuals for the gameplay afterwards (I can hear the audio though). Switching to SteamVR as my OpenXR runtime allows me to get past the cut scene but the game itself is very jittery and keeps freezing every few seconds and/or eventually crashes making it pretty much unplayable :( I've tried using both virtual desktop and steam link but both are producing the same results.

I am running the latest release of JKXR.

**Comment by baggyg** [comment]
This is a known issue and an error on Virtual Desktop's side. They are aware of it and have fixed but we're awaiting a new release which includes it. 

Either downgrade to previous version of VD or use alternative (SteamVR / AirLink-OculusXR)

**Comment by Zerthick** [comment]
@baggyg Yes I've become aware of the issues with Virtual Desktop, however I switched to steam link and SteamVR is still very jittery and crashes.

**Comment by baggyg** [comment]
Make sure you have the latest version of JKXR. We fixed up things that make that better. However none of us have found Steam Link particularly great. 

Also make sure Steam hasn't put some crazy resolution on it. 

Airlink is a far superior experience IMO.
