### ISSUE TITLE
PCVR / Index Random pausing. Computer plenty powerful.

### ISSUE THREAD

**Issue by beep2bleep** [DrBeef/JKXR#13]
I'm getting random PCVR stutters, I've attached a YT video showing the problem. https://youtu.be/L8o-wLFEwl8 PC is 7800xt, 4090. Occures at 05 and 1:04.

**Comment by baggyg** [comment]
If you have a different hard drive, you can try moving the game / port to that one and running there. We've had some reports that certain hard drives cause similar problems.

**Comment by DrBeef** [comment]
We literally figured out the cause of this issue at the weekend. There will be an update to the PCVR builds coming very soon to fix it properly.

**Comment by beep2bleep** [comment]
Thanks for fixing the issue.
