### ISSUE TITLE
PCVR Index controllers not recognised by the game

### ISSUE THREAD

**Issue by hypsin0** [DrBeef/JKXR#17]
I do not feel like there is much to say: My controllers do not work in this game whatsoever -- no button inputs, no tracking, nothing. They work just fine in other games and in SteamVR Home directly prior to launching the game, and I can see my controllers when I enter the Steam Overlay. My controllers have bindings in the game and all that. As a result. this VR port is completely unplayable.

**Comment by baggyg** [comment]
Make sure the window has focus (In other words once the JKXR window launches click in it with your mouse)

**Comment by hypsin0** [comment]
> Make sure the window has focus (In other words once the JKXR window launches click in it with your mouse)

I did do that, and I can confirm that I also cannot navigate the menus with my mouse — the only way to get into the actual game that I found was by using the up and down arrows and the enter key.

**Comment by baggyg** [comment]
Really need more information to be able to replicate then. I've fully tested this with Valve Index and it worked without issue for me.

**Comment by hypsin0** [comment]
What kind of information would be helpful?

**Comment by baggyg** [comment]
Probably best if you could do a screen grab video, so we can try and spot anything out of the ordinary. 

I'd recommend OBS to capture the entire desktop.

**Comment by hypsin0** [comment]
Well, this is embarrassing: I have restarted my computer, and it seems like it now works with no further changes... Thank you for your time

**Comment by baggyg** [comment]
Glad to hear it. Enjoy
