### ISSUE TITLE
Latest release (1.1.28) is unavailable on SideQuest

### ISSUE THREAD

**Issue by Hi-Angel** [DrBeef/JKXR#21]
It seems, when release was made it somehow got forgotten to push update over to SideQuest repo. Latest release availble there is 1.1.27 where the actual latest is 1.1.28.

# Steps to reproduce

1. Go [to the SideQuest application page](https://sidequestvr.com/app/15472)
2. Look at the description square on the right

## Expected

It would say version is 1.1.28

## Actual

The version is 1.1.27

![Screenshot_20241022_205718](https://github.com/user-attachments/assets/dbc1ebe3-944a-4e16-bc60-0c4872eeb6fb)

**Comment by DrBeef** [comment]
1.1.28 was a PCVR build update only, it fixed an issue that some PCVR users were having with the app periodically freezing. There was no change for Android so no sidequest update was necessary.
