### ISSUE TITLE
[Valve Index] Grip Strength Threshold Too High

### ISSUE THREAD

**Issue by Seadriss** [DrBeef/JKXR#5]
I played for about two hours on a Valve Index and the mod/port works great aside from one issue :   
The amount of grip you need to exert for the game to bring up the weapon/force menu and for the two handed grab of weapons.  
Unless I grip the controllers very tightly I get kicked out of those constantly, and it gets uncomfortable fast.  

Providing a slider to set this threshold in the comfort option would probably solve this issue entirely, allowing each player to find the balance that fits them the most. (If such an option exist I have missed it)

Thanks for your great work.

**Comment by baggyg** [comment]
Yes, we ran out of time to add this but a slider is the best outcome. If nothing else it would be good to have this as a cvar. I'll make sure it gets added in the 1st post-launch release. 

At the moment the setting is 0.7 as we felt it triggered a little too easily.  I think a better alternative may be a trigger value of around that, but a lower filter when held. So 0.7 to trigger, 0.5 to release. We'll figure it out.

**Comment by baggyg** [comment]
Added trigger levels in latest release:

https://github.com/DrBeef/JKXR/releases/tag/1.1.27

Defaults should be a lot better, but if not you can manually alter via the config file.
