### ISSUE TITLE
[HTC Vive] Vive Wands cannot crouch and slow movement speed

### ISSUE THREAD

**Issue by SeriousSpy** [DrBeef/JKXR#7]
With the default setup, Vive Wands have seemingly no binding to crouch/roll, and movement speed is too low to pass the Force Speed test in the tutorial (possibly because of the inability to crouch).

**Comment by SeriousSpy** [comment]
(Note, temporary solution in this case was to simply load the save in pancake mode, roll under the door, save again and reload in VR)

**Comment by baggyg** [comment]
Thanks, I'll check this out and come back to you. 

Regarding movement speed, I think its set to always run. If you turn that off in the options there are toggles for run speed.

**Comment by baggyg** [comment]
Fixed missing Vive Controls is latest release:

https://github.com/DrBeef/JKXR/releases/tag/1.1.27
