### ISSUE TITLE
Is HP Reverb G2 Supported for PCVR? Unable to launch JKA or JKO

### ISSUE THREAD

**Issue by jpcarstech** [DrBeef/JKXR#8]
As the title states, not sure if HP Reverb G2 V2 is supported. I've tried launching for both JKO and JKA and nothing happens. Any tips or is there a log I can provide to help? Thanks.

**Comment by baggyg** [comment]
I'm really not sure what the state of WMR is, especially with Microsoft removing support. All I can say is that none of the team have a WMR to try and we didn't add an interaction profile. 

However, I don't think that is the problem in this instance. As long as G2 can use SteamVR and SteamVR is set to the default OpenXR runtime, it should work (by emulating Touch controllers). 

Ensure that the shortcut is pointing to the right folder and that the extra files are there. Worse case scenario you can manually drag the files to the right place.

**Comment by jpcarstech** [comment]
Thanks for the quick response. I was able to get it working. If anyone else with a Reverb G2 wanders here, you have to take your headset off, go to the Steam VR Status app>Hamburger menu>Settings>OpenXR.
Set your OpenXR Runtime to SteamVR. You may need to install OpenXR for Windows Mixed Reality from the Windows store too. I am not sure if that helped here. But as soon as I set my Open XR Runtime to Steam VR I was able to play.

**Comment by baggyg** [comment]
Great! We'll update the readme on github to reflect this.
